### ISSUE TITLE
Format with multiples named placeholders

### ISSUE THREAD

**Issue by GitPotTime** [axuno/SmartFormat#119]
When I use one named placeholders, the format work, but when I add multiple named placeholders. An exception is throw `SmartFormat.Core.Formatting.FormattingException`
How can I use multiple named placeholders?

**Comment by axunonb** [comment]
You can use multiple placeholders [as pointed out in the Wiki](https://github.com/axuno/SmartFormat/wiki/Placeholders-and-Nesting). Without a working code sample we can't tell you more, sorry.

**Comment by GitPotTime** [comment]
For exemple, this work perfectly: `Smart.Format("I like {Food}", new[] { new { Food = "Chips"  } })` return me `I like Chips`
but `Smart.Format("I like {Food} whereas {Drink} is better", new[] { new { Food = "Chips" } }, new[] { new { Drink = "Water" } })` return me `I like  whereas  is better`

**Comment by axunonb** [comment]
There are several ways to achieve the desired output.
```csharp
Smart.Default.Settings.FormatErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;
Smart.Default.Settings.ParseErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;

// Throws exception
// var doesNotWork = Smart.Format("I like {Food} whereas {Drink} is better", new[] { new { Food = "Chips" } }, new[] { new { Drink = "Water" } });

// one option:
var works1 = Smart.Format("I like {0:{Food}} whereas {1:{Drink}} is better", new { Food = "Chips" }, new { Drink = "Water" });

// another option:
var so = new SmartObjects(new object[] { new { Food = "Chips" }, new { Drink = "Water" } });
var works2 = Smart.Format("I like {Food} whereas {Drink} is better", so);
```
Please read our Wiki.
