### ISSUE TITLE
Escaped backslash fails

### ISSUE THREAD

**Issue by blalonde** [axuno/SmartFormat#121]
```csharp
        [Fact]
        public void Test()
        {
            var result = Smart.Format("\\", new List<object>());
        }
```
Fails, while it doesn't with string.Format

**Comment by axunonb** [comment]
Maybe you could describe a bit more elaborately, like
- what is the ```Assert``` in your unit test - just one backslash, as you give no variable, or two?
- what kind of "object" is it?
- what are your ```Settings``` in ```SmartFormat.Default```?

**Comment by axunonb** [comment]
No reply
