### ISSUE TITLE
Is it possible to use nested placeholders?

### ISSUE THREAD

**Issue by d-sky** [axuno/SmartFormat#123]
For example, having template which is partially consists of another template:
`{Field{Number}} `
And passing object like
```
var data = new 
{
    Field1 = "expected output",
    Number = 1
};
```
As I expected, it should first replace inner placeholder `{Number}` to **1**, so it becomes `{Field1}`, and then being replaced with value from **Field1** field.

**Comment by axunonb** [comment]
No, this is not implemented, also not with ```string.Format``` btw.
