### ISSUE TITLE
Would it be difficult to add netstandard 2.1 support? (dotnet core 3.0 OS-agnostic support?)

### ISSUE THREAD

**Issue by x10an14** [axuno/SmartFormat#124]
As subject says, this issue is meant to chart the obstacles to overcome so as to get dotnet-core 3+ (and preferably os-agnosticism) support.

If, and only if however, said support already is in-place, then consider this a request to update the frameworks setting in the csproj to match the above request for netstandard2.1 =)

**Comment by axunonb** [comment]
SmartFormat 2.5.0 does not make use of the new features which are coming with NetStandard2.1. Still, this target framework can be served as well. We just compiled a package including NetStandard2.1 binaries (attached to this post). Does this supply what you are aiming at?
[SmartFormat.NET.2.5.0.nupkg.zip](https://github.com/axuno/SmartFormat/files/3910779/SmartFormat.NET.2.5.0.nupkg.zip)

**Comment by axunonb** [comment]
Does the package including NeStandard2.1 supply what you are aiming at?
(to install, please remove the .zip extension of the file)

**Comment by x10an14** [comment]
Apologies for delayed response!

My work re-prioritized my task list so I've had to let this lie for now, I'll see if I can figure out how to put `.nupkg` binaries on some library PATH for `dotnet` on Linux (I'm on Linux).

I'll let you know if I manage to test it!

**Comment by x10an14** [comment]
First 10 minutes of googling and testing doesn't seem to offer a solution on how to use Microsoft's `dotnet` tool to reference/install/user a `.nupkg` file in a `dotnet core` project... =/

**Comment by axunonb** [comment]
Closed with release [v2.5.1](https://github.com/axuno/SmartFormat/releases/tag/v2.5.1.0)
