### ISSUE TITLE
Named placeholders nullable

### ISSUE THREAD

**Issue by imtrobin** [axuno/SmartFormat#128]
Hi, just found this gem. Is it possible to pass in null for Named Placeholders and get it to work?

**Comment by axunonb** [comment]
Yes, that is possible. You can even implement a special treatment for ```null``` values. Have a look at the [Choose Formatter](https://github.com/axuno/SmartFormat/wiki/Choose) sample.

**Comment by imtrobin** [comment]
Got it working , thanks
