### ISSUE TITLE
2.5.1 breaks backwards compatibility. should be v3.0

### ISSUE THREAD

**Issue by goldsam** [axuno/SmartFormat#129]
v 2.5.1 broke compatibility with older versions of the .Net framework. The version number should have been 3.0.0 to indicate this if following semantic versioning.

**Comment by axunonb** [comment]
Sorry if you're experiencing incompatibilities.
Could you elaborate how or where exactly the API compatibility has been broken? You think there is a point to unlist v2.5.1?

**Comment by goldsam** [comment]
my team is still forced to use .net 4.6.1 on client project. We were just a bit surprised. Not sure if there is a technical reason for dropping support. we were just surprised and perhaps a bit disappointed.
