### ISSUE TITLE
Only subset of RegEx expressions are considered as valid for IsMatch formatter

### ISSUE THREAD

**Issue by rich-ng** [axuno/SmartFormat#131]
After review the documentation and code, there doesn't seem to be a way to escape colons and parenthesis that's part of the FormatterOptions.  An example would be trying to use the IsMatch extension with a regex expression that contains a colon.

**Comment by axunonb** [comment]
Generally speaking without sample code: true, there is a limitation connected to ```string.Format``` compatibility.
We're always happy about proposals for improvement.

**Comment by rich-ng** [comment]
Any of the following won't work because of how the parser parses the format.

```
Smart.Format("{0:ismatch(^\\d+):Valid Time|Invalid Time}", "12:30");
Smart.Format("{0:ismatch(:):Valid Time|Invalid Time}", "12:30");
Smart.Format("{0:ismatch(()):Valid Time|Invalid Time}", "12:30");
```

What if we add the concept of a literal FormatterOptions?  That concept would only exist within the realm of the FormatterOptions.  Something like the following

```
Smart.Format("{0:ismatch(`^\\d+`):Valid Time|Invalid Time}", "12:30");
Smart.Format("{0:ismatch(`:`):Valid Time|Invalid Time}", "12:30");
Smart.Format("{0:ismatch(`()`):Valid Time|Invalid Time}", "12:30");
```

Looking at the parser, that change seems pretty doable.  What are your thoughts?

**Comment by axunonb** [comment]
If I understand your idea correctly, you would introduce the backtick as another "magic character" to be handled by the parser. As we only have a single parser for the whole input string, this would mean a breaking change for all formatters in case the backtick is part of the input string, right? 
You could also have a look at the discussion at https://github.com/axuno/SmartFormat/issues/88

**Comment by rich-ng** [comment]
Yes that would be a breaking change.  My actual issue is that I'm trying to create an extension that takes in a timespan and apply the timespan to a date.  I'm unable to do that because the string interpretation timespan has colons and there's no way to tell the parser that the colon is part of the timespan and not a delimiter.  I was just using the ismatch extension as an example because the root of the problem still stands.  I was able to solve my problem by using days instead of timespan but I wanted to bring up the issue because I think it'll be a valuable addition to the project.

**Comment by axunonb** [comment]
You may have a good reason for using the ```TimeSpan``` in its ```string``` representation, but wouldn't ```TimeFormatter```  or ```ConditionalFormatter``` be a way to solve the problem? I mean: ```SmartFormat``` is a formatter rather than a validator.

**Comment by rich-ng** [comment]
The validation aspect was just an example to demonstrate issue with the parser.  This is the code that I was trying to get working when I stumbled onto the issue.  That won't work because of the input for the modifydate extension.  As mentioned there are ways around the issue, but the issue is still there.

```
public class ModifyDateFormatter : IFormatter
{
	public string[] Names { get; set; } = new[] { "modifydate" };

	public bool TryEvaluateFormat(IFormattingInfo formattingInfo)
	{
		if (formattingInfo.CurrentValue is DateTime datetime)
		{
			if (TimeSpan.TryParse(formattingInfo.FormatterOptions, out var value))
			{
				var datetimeFormat = formattingInfo.Format.RawText;
				formattingInfo.Write(datetime.Add(value).ToString(datetimeFormat));

				return true;
			}
		}

		return false;
	}
}
```

```
public string RenderFormat(string format)
{
	SmartFormat.Smart.Default.AddExtensions(new ModifyDateFormatter());

	return SmartFormat.Smart.Format(format, new
	{
		date = DateTime.Now
	});
}
```
```
RenderFormat("{date:modifydate(-1.00:00:00):MMMM - yyyy}");
```

**Comment by axunonb** [comment]
Out of question, the issue is there, and I'll have to find some time to re-engineer this part for a version 3.x.
In your sample you could omit the colons alltogether by calling the formatter a bit different:
```RenderFormat("{date:modifydate(-1,0,0,0,MMMM,yyyy)}");```
Not that bad either.

**Comment by axunonb** [comment]
Hi
It's been a while... Now we're on the way to a v3 release. It is now possible to include "any character anywhere", as long as it is properly escaped. Finally we did not introduce an additional magic character, but tool special care for characters when parsing format options.

Escaping for `RegEx` patterns actually looks a bit weird, but there is a helper method `EscapedLiteral.EscapeCharLiterals` that returns a properly escaped option string.

Could you **please** have a look, whether we have covered each of the issues you had in mind?
Do you think, a `RegEx.Replace` extension would also make sense?

For your convenience we've included a nupkg (uploaded with zip extension) with the current v3-draft binaries.
[SmartFormat.NET.3.0.0-draft.nupkg.zip](https://github.com/axuno/SmartFormat/files/6604487/SmartFormat.NET.3.0.0-draft.nupkg.zip)

Here is the test case taken from your example ([more examples](https://github.com/axuno/SmartFormat/blob/version/v3.0/src/SmartFormat.Tests/Extensions/IsMatchFormatterTests.cs)):

```csharp
[TestCase(@"\d+", "12:30", true)] // escaped (escape backslash): "\\d+"
[TestCase(@"\:", "12:30", true)] // escaped (escape backslash, regex escaped colon): "\\\:"
[TestCase(@"\(\)", "12:30", false)] // escaped (escape backslash, regex escaped parenthesis): "\\\(\\\)"
public void Test_Issue_131(string pattern, string input, bool shouldMatch)
{
    var regExOptions = RegexOptions.None;
    ((IsMatchFormatter) _formatter.FormatterExtensions.First(fex =>
        fex.GetType() == typeof(IsMatchFormatter))).RegexOptions = regExOptions;

    var regEx = new Regex(pattern, regExOptions);
    var optionsEscaped = new string(EscapedLiteral.EscapeCharLiterals('\\', pattern, 0, pattern.Length, true).ToArray());
    var result = _formatter.Format("{0:ismatch(" + optionsEscaped + "):true|false}", input);

    Assert.That(regEx.Match(input).Success, Is.EqualTo(shouldMatch), "RegEx pattern match");
    Assert.That(result, shouldMatch ? Is.EqualTo("true") : Is.EqualTo("false"), "IsMatchFormatter pattern match");
}
```

**Comment by rich-ng** [comment]
@axunonb

I will take a look at the changes.  Thank you!

**Comment by axunonb** [comment]
@rich-ng Could you find some time for looking into the proposed solution?

**Comment by rich-ng** [comment]
@axunonb I looked over the solution.  I think that'll work in my case.

I'm not sure if the extension method would make sense because I don't know how other people are using the utility.  For me, the biggest draw is the fact that I can set the string format at runtime as oppose to compile time.  With my usage of the utility I'll be pulling the format from a data store so the extension method would not help me in that case.

**Comment by axunonb** [comment]
@rich-ng Thanks for that. Could you elaborate the reason why you can't use the format coming from your data store? What would be the precondition to make it possible?

**Comment by Payaspx** [comment]
> After review the documentation and code, there doesn't seem to be a way to escape colons and parenthesis that's part of the FormatterOptions. An example would be trying to use the IsMatch extension with a regex expression that contains a colon.

**Comment by axunonb** [comment]
Posted in wrong repo - belongs to https://github.com/axuno/SmartFormat https://github.com/axuno/SmartFormat/issues/131#issuecomment-855424258

**Comment by axunonb** [comment]
> 
> 
> > After review the documentation and code, there doesn't seem to be a way to escape colons and parenthesis that's part of the FormatterOptions. An example would be trying to use the IsMatch extension with a regex expression that contains a colon.

The colon is covered in https://github.com/axuno/SmartFormat/issues/131#issuecomment-855424258
```csharp 
[TestCase(@"\:", "12:30", true)] // escaped (escape backslash, regex escaped colon): "\\\:"
```
So this should actually work, shouldn't it?
