### ISSUE TITLE
Substring is empty if specified length is too long

### ISSUE THREAD

**Issue by andersjonsson** [axuno/SmartFormat#141]
Using data from your example on https://github.com/axuno/SmartFormat/wiki/SubString

```
var people = new List<object>
{new {Name = "Long John", City = "New York"}, new {Name = "Short Mary", City = "Massachusetts"},};

Smart.Format("{Name:substr(5)}", people.First());
// result: "John"

Smart.Format("{City:substr(0,3)}", people.First());
// result: "New"
	
Smart.Format("{City:substr(0,9)}", people.First());
// result: "", expected: "New York"
```

I'd like to use substring as a way to limit max-length of a particular output, but now I just get "" on short items.

**Comment by axunonb** [comment]
> // result: "", expected: "New York"

"New York" can be expected with `Smart.Format("{City:substr(0,8)}"`
`"New York".Substring(0,9)` will throw an `ArgumentOutOfRangeException`
Agree?

**Comment by andersjonsson** [comment]
Yes, that's correct. However SmartFormat mostly seems to avoid throwing exceptions and I would agree that this is a good strategy for a formatting lib

Right now SmartFormat returns "" but I think it makes more sense to return the full string.

My reasoning is that the SubStringFormatter will mostly be used to limit maximum length,
as in my own use-case. For that reason neither an exception or "" is expected.

I submitted a PR if you are interested.

**Comment by andersjonsson** [comment]
> Yes, that's correct. However SmartFormat mostly avoids throwing exceptions and I would agree that this is a good strategy for a formatting lib
> 
> Right now SmartFormat returns "" but I think it makes more sense to return the full string.
> 
> My reasoning is that the SubStringFormatter will mostly be used to limit maximum length,
> as in my own use-case. For that reason neither an exception or "" is expected.
> 
> I submitted a PR if you are interested.

Let's keep the discussion in the PR
