### ISSUE TITLE
Problems formatting HTML

### ISSUE THREAD

**Issue by hugoqribeiro** [axuno/SmartFormat#147]
Hi.

I have the following code to format a string containing HTML:

```charp
Dictionary<string, object> parameters = new Dictionary<string, object>()
{
    ["IDSBrand"] = "MyBrand",
    ["IDSColor1"] = "MyColor",
    ["IDSSalutation"] = "MySalutation",
    ["IDSBody"] = "MyBody",
    ["IDSActionLink"] = "MyActionLink",
    ["IDSAction"] = "MyAction",
    ["IDSTimestampDescription"] = "MyTimestampDescription",
    ["IDSCopyrightDescription"] = "MyCopyrightDescription",
    ["NSTimestampEN"] = "MyTimestamp"
};

string inputFile = File.ReadAllText(Path.Combine(Environment.CurrentDirectory, "Files\\InputHtml.txt"));

SmartFormatter formatter = Smart.CreateDefaultSmartFormat();
formatter.Settings.CaseSensitivity = CaseSensitivityType.CaseInsensitive;
formatter.Settings.ParseErrorAction = ErrorAction.MaintainTokens;
formatter.Settings.FormatErrorAction = ErrorAction.MaintainTokens;
formatter.Settings.ConvertCharacterStringLiterals = false;

string outputFile = formatter.Format(inputFile, parameters);

File.WriteAllText(Path.Combine(Environment.CurrentDirectory, "Files\\OutputHtml262.txt"), outputFile);
```

If I run this with version 2.6.2 the formatter does nothing (no replacements).

If I run this with version 2.5.2 the formatter works more or less correctly (does the replacements but it introduces some errors in the HTML).

This is visible with the following files:

[InputHtml.txt](https://www.dropbox.com/s/iyu2yvceko8o89y/InputHtml.txt?dl=0) - the input HTML
[OutputHtml262.txt](https://www.dropbox.com/s/w6crcd6zr4glpzl/OutputHtml262.txt?dl=0) - the output produced with 2.6.2
[OutputHtml252.txt](https://www.dropbox.com/s/alka8psjkkmje2c/OutputHtml252.txt?dl=0) - the output produced with 2.5.2
[OutputHtml.txt](https://www.dropbox.com/s/se8urnj2wxnbw4q/OutputHtml.txt?dl=0) - the expected output

Comparing 2.6.2 with the expected output... no replacements at all.
Comparing 2.5.2 with the expected output... replacements OK but errors in HTML (e.g. line 68, col 9).

Is this a bug? Something that I need to change in the upgrade from 2.5.2 to 2.6.2?

**Comment by axunonb** [comment]
Parsing HTML works fine, except when it includes CSS styles and JavaScript. Both have curly braces in their syntax, which Smart.Format interprets as `{ placeholders }`. This did not work with any Smart.Format version. 
You can do the following:
1. Replace the CSS style section of your HTML with a placeholder for Smart.Format  (e.g. `{ CssPlaceholder }`) and fill it with the content of a variable.
2. Load the CSS styles and JavaScripts from separate files (most simple)
3. Use [AngleSharp](https://github.com/AngleSharp/AngleSharp) to exclude `style` and `script` tags (e.g. only work with Smart.Format on the `body` tag)

**Comment by hugoqribeiro** [comment]
The HTML is user input, including the variables to replace. It makes it hard to implement your suggestions. :)

Did you see the difference between version 2.5.2 and 2.6.2?
One would expect at least the same behavior, given that I'm using MaintainTokens.

**Comment by axunonb** [comment]
If it is all user input, it takes only few lines of code to solve with [AngleSharp](https://github.com/AngleSharp/AngleSharp):
```csharp
using AngleSharp;
using AngleSharp.Html.Dom;
using AngleSharp.Html.Parser;
// Create a new parser front-end (can be re-used)
var parser = new HtmlParser();
// Get the DOM representation
IHtmlDocument htmlDocument = parser.ParseDocument(yourUserHtmlInput);
// htmlDocument.Body.InnerHtml contains the result
htmlDocument.Body.InnerHtml = Smart.Format(htmlDocument.Body.InnerHtml, yourDataItems);
```
Hope this helps.

I did not analyze the differences between versions, because HTML containing CSS styles and/or JavaScript cannot be processed reliably with `Smart.Format` as per the curly braces both are using.

**Comment by hugoqribeiro** [comment]
Thank you @axunonb

**Comment by axunonb** [comment]
Welcome
