### ISSUE TITLE
Generic implementation for Alignment

### ISSUE THREAD

**Issue by karljj1** [axuno/SmartFormat#150]
Hi,
Im looking at one of the examples in the code:
Placeholder.cs has this example:

**"{Items.Length,10:choose(1,2,3):one|two|three}"**

For some reason the alignment is not being applied. It looks like its only done in the Default Formatter and its not being applied in this example for me. Any ideas? Also I had to change it to use | instead of , for the format values.

**Comment by axunonb** [comment]
Thanks for the hint.
The examples in xmldoc should of course be correct. But you're better off having a look at the unit tests, simply because they all must work.

**Comment by axunonb** [comment]
If a custom formatter is used, the default formatter will not be called. That's why there's no alignment.
Taking care of `Alignment` must take place in the custom formatter.
Wonder whether this brings any benefit for the standard `ChooseFormatter`.

**Comment by axunonb** [comment]
Should `Alignment` become part of `IFormatter`?
Then it was clear this must be tackled by a formatter.

**Comment by karljj1** [comment]
> Should `Alignment` become part of `IFormatter`?
> Then it was clear this must be tackled by a formatter (throw `NotImplementedException`, do nothing, deal like `string.Format`).

Yeah it makes sense to do that. Its confusing to a user at the moment as its only applied when 1 type of formatter is used.

**Comment by axunonb** [comment]
Still thinking about what's better to add to `IFormatter`?

`void AlignFormat();` 
or 
`Action<int, char> AlignFormat { get; set; }`  (here, the fill character instead of blank could become part of the implementation)

Feature for v3.

**Comment by karljj1** [comment]
Isn't it essentially the same thing for all of them? If the formatter handles the item then apply the alignment. Maybe it could be handled in a generic way so that it does not need to be implemented by each formatter?

**Comment by axunonb** [comment]
Will consider this option, too. Definitely a feature request.

**Comment by axunonb** [comment]
**version/v3:**
Handling alignment will go to `FormattingInfo`, while `SmartFormatter.EvaluateSelectors` will set `FormattingInfo.Alignment` from the parsed `Format`. This way, alignment will be available to all formatters out-of-the-box.

**Comment by axunonb** [comment]
Closed with "Alignment option always available" (#174)
