### ISSUE TITLE
How to format properties with possible null values?

### ISSUE THREAD

**Issue by mikasoukhov** [axuno/SmartFormat#156]
To make a possible expression like:

`{Product.Owner.Company?.Name:SelfEmplo}`

**Comment by axunonb** [comment]
Looks clear what you mean with `Company?.Name` in terms of `Nullable`. Which role does `:SelfEmplo` play here?
Have you considered to use the *Choose* formatter?
```Csharp
// set the City to null or a string literal:
var data = new {Person = new {FirstName = "John", LastName= "Long", Address = new { Country = "USA", City = default(string)}}};
var result = Smart.Format("{Person:{Address.City:choose(null):|{}} }", data);
```

**Comment by mikasoukhov** [comment]
Here is the example

```
class Address
{
	public string Country;
	public string City;
}

class Person
{
	public string FirstName;
	public string LastName;
	public Address Address;
}

var data = new {Person = new Person {FirstName = "John", LastName= "Long", Address = new Address{ Country = "USA", City = ""}}};
Smart.Default.Parser.UseAlternativeEscapeChar(); // will allow '}}}' to achieve an empty string in case of null
Console.WriteLine(Smart.Format("{Person.Address.City}", data));
// the person decided remove his own personal information
data.Person.Address = null;
Console.WriteLine(Smart.Format("{Person.Address.City}", data)); // here we get some absolutelly non relative error message
```

Here are two ways.

The first one - to make SF ignore nullable values when he tries to walk on a physical expression tree (see Eval in ASP.NET).

And another one - extended format with some conditional format. Like you did, but it is toooo far away from native C# nullable (with ? char) syntax.

**Comment by axunonb** [comment]
>  here we get some absolutely non relative error message
```
Error parsing format string: Could not evaluate the selector "City" at 16
{Person.Address.City}
----------------^
```
Remember it is no only about rendering selectors from class instances or anonymous types. SF also processes JSON, XML and cascading dictionaries. Which more comprehensive error message would you expect?

> to make SF ignore nullable values when he tries to walk on a physical expression tree

There is a setting to achieve this:
```Csharp
Smart.Default.Settings.FormatErrorAction = ErrorAction.Ignore;
```

However, I like the idea of the desired `nullable` notation, see #157
