### ISSUE TITLE
Could you suggest the best way to call default formatter on modified argument?

### ISSUE THREAD

**Issue by lekrus** [axuno/SmartFormat#163]
Hello,

Could you please suggest the best approach for a custom formatter if it's needed to update some arguments, but then apply the standard formatter? Currently I used the code from standard ListFormatter to create a new Format object, but, probably, there is a better option to achieve the same?
```c#
private class TestFormatter : IFormatter {
	public bool TryEvaluateFormat(IFormattingInfo formattingInfo) {
		if (!(formattingInfo.CurrentValue is DateTime dt) || formattingInfo.Format == null || 
                    formattingInfo.Format.HasNested || dt.Kind == DateTimeKind.Local) return false;

		var newItemFormat = new Format(formattingInfo.FormatDetails.Settings, itemFormat.baseString) {
			startIndex = itemFormat.startIndex,
			endIndex = itemFormat.endIndex,
			HasNested = true
		};
		var newPlaceholder = new Placeholder(formattingInfo.FormatDetails.Settings, newItemFormat, 
                   itemFormat.startIndex, 0) {
			Format = itemFormat,
			endIndex = itemFormat.endIndex
		};
		newItemFormat.Items.Add(newPlaceholder);		

		formattingInfo.Write(newItemFormat, dt.ToLocalTime());
		return true;
	}

	public string[] Names { get; set; } = {string.Empty};
}
````

Thanks a lot!

**Comment by axunonb** [comment]
Hi
Not quite sure what you're aiming at.
* The `TestFormatter`code doesn't look like the `ListFormatter`, but anyway: Which relevance does the code have to achieve your aim?
> custom formatter if it's needed to update some arguments,
* Which arguments?
* Are you aiming at using the result string of your `TestFormatter` as the format string another formatter in a second step?

**Comment by lekrus** [comment]
Hi, thank you for the prompt reply!

Let me explain In other words: my goal is to add some pre-processing to values being formatted before applying formatting.
Like if we call Format("{0:MMM}", someDate), I'd like to update someDate (like changing the time zone or changing a date's kind) before applying format. 
When I implement a custom IFormatter I get access to the value being formatted and the format itself.
But I'd like to call the default formatter after processing the value, just to use all other features (nested placeholders, etc).
In the sample above, I could have just written:
```c#
formattingInfo.Write(dt.ToLocalTime().ToString(formattingInfo.Format.RawText));
```
so, native String.Format does date formatting to string, but I thought I could use formattingInfo.FormatDetails.Formatter for that purpose?

And I'd like to have that pre-processing on formatting level, as I might have a very big object with many properties, while formatting selector only gets a single property, so it's much faster. That's why I'm trying to preprocess the value on the "leaf" level, just before it's formatted.

Hope this explains my question better.

The ListFormatter mentioned only because I used some parts of its code for that TestFormatter.

Thanks!

**Comment by axunonb** [comment]
Hm, I'm still a bit in doubt...
Hope this is of any help:

1. Changing values before formatting

* Changing input variables should rather be accomplished in an `ISource` than in an `IFormatter`
* Your `ISource` gets invoked by `TryEvaluateSelector(ISelectorInfo selectorInfo)` and `selectorInfo.Result` should be set by it. 
* Depending on the type of input variables, you could change one of the existing `ISource` extensions. You mention 'very big objects', to you'll probably go for `ReflectionSource`. (Btw., in the next release, [`IReflectionSource`](https://github.com/axuno/SmartFormat/blob/version/v3.0/src/SmartFormat/Extensions/ReflectionSource.cs) will have type caching out-of-the box. This will give a nice performance increase by factor 4.)

2. Call the default formatter after processing the value

* The logic for nested placeholders etc. isn't part of the `DefaultFormatter`. This is all figured out in the `Parser`.
* An `IFormatter` only cares about the string representation of one specific variable at a time.

Remark: 
Currently, if you have your custom `IFormatter`, the *Alignment* feature of the `DefaultFormatter` does not exist. That's the only thing you might copy from there, if you need it. In the next release, *Alignment* will be provided to `IFormatters` using an abstract class.

**Comment by lekrus** [comment]
Thank you for the feedback.

In regards to `ISource`, I initially tried that, but its `selectorInfo.CurrentValue` equals to that whole object, not specific property that is selected.
The main idea to achieve was to make it a generic extensions that can be called differently, like:
```c#
var testObj = new TestObj { DateField = new DateTime() };
Format("test from obj: {TestObj.DateField:MMM-hh}, and test from date value: {1:MMM-hh}", testObj, new DateTime());
```
in other words, I do not know what kind of source will be passed to the formatter, just need to update DateTime-only values on the very last-mile, before they are formatted.
When using `ISource` the first value in selector will be `testObj`, while I need the exact value of `DateField`. And it's possible to have multiple nested objects there or other types of sources, so I had to use custom `IFormatter`.

After our discussion, I think that the best / simplest option would be just going with a simple `ToString` in my custom `IFormatter`?:
```c#
formattingInfo.Write(dt.ToLocalTime().ToString(formattingInfo.Format.RawText));
```

**Comment by axunonb** [comment]
> but its `selectorInfo.CurrentValue` equals to that whole object, not specific property that is selected

Disagree.

When `ISource.TryEvaluateSelector(ISelectorInfo selectorInfo)` is called the **first** time, you'll get an instance of the first selector, which is`testObj`, true. But the `ISource` method is **called for each selector**.

So for the **second** selector `DateField`. `selectorInfo.CurrentValue == <DateTime>` (type `DateTime`), and `selectorInfo.SelectorText == "DateField"`. Then you know the field name, same as you would know it in the formatter.

**Comment by lekrus** [comment]
Well, for me it works differently from what you described, probably I'm doing something wrong.

My custom `ISource`:
```c#
public bool TryEvaluateSelector(ISelectorInfo selectorInfo) {
	var val = selectorInfo.CurrentValue;
	Log.Debug("Type={0}, Selector={1}", val?.GetType().Name, selectorInfo.SelectorText);
	return false;
}
```
Call:
```c#
private class TestObj {
	public DateTime DateField { get; set; }
	public TestObj Nested { get; set; }
}
var test = smartFormatter.Format("test from obj: {Nested.DateField:MMM-hh}", testObj);
```
`TryEvaluateSelector` is indeed called twice, but both times `selectorInfo.CurrentValue` is of type TestObj (and I think it's correct, because a specific `ISource` should know how to extract value from `CurrentValue` using Selector), e.g. I receive:
```
Type=TestObj, Selector=Nested
Type=TestObj, Selector=DateField
```
in logs.

**Comment by axunonb** [comment]
Aha, you're always returning `false` in method `TryEvaluateSelector`. But you should return `true`, if it could be evaluated successfully.

**Comment by lekrus** [comment]
Yes, I return `false` there, because I just need plain `DateTime` values, e.g. when I receive a `DateTime` value - I would return `true`, but that never happens.
In any case I guess that custom `IFormatter` will be a good implementation for my needs, thank you for useful hints and the great library!

**Comment by axunonb** [comment]
My recommendation is to use the `ReflectionSource` and modify as needed.
Thanks for using Smart.Format.
