### ISSUE TITLE
Be smart about {}

### ISSUE THREAD

**Issue by jgauffin** [axuno/SmartFormat#19]
Currently you accept any character into the {} string. So if we have code:

```
foreach (var key in collection)
{
    //bla bla
}
```

If will destroy that block. At least make sure that there are no tabs/spaces/newlines in the block. You shouldn't have to escape the curly braces if the formatter can't use the block.

**Comment by vector-man** [comment]
Is there a property build in that will allow you to change the placeholder characters or do I have to modify the library?

**Comment by SeriousM** [comment]
I guess it's somewhere in https://github.com/scottrippey/SmartFormat.NET/tree/master/src/SmartFormat/Core/Parsing .
@scottrippey, can you confirm?

**Comment by scottrippey** [comment]
I honestly thought it was built in to change the symbols, but after taking a look at `Parser.cs`, I can see that it's hard coded. Perhaps this could be a feature request.

**Comment by vector-man** [comment]
Should I create a feature request for this?

**Comment by scottrippey** [comment]
Yeah, create it as a feature request, on a separate thread.
