### ISSUE TITLE
Nesting into a template?

### ISSUE THREAD

**Issue by karljj1** [axuno/SmartFormat#205]
Hello,
I had this question from one of our users and could not figure out if it was possible.
They want to use the template formatter to apply decoration to the results of some text. For example they want to put the results into some rich text:
template: `<color=red>{}</color>`

Is it possible to pass the results of a smart format string into another formatter?

E.G
Something like:
`{You have {0} items}:template(red)}`

Which then becomes

`<color=red>You have 10 items</color>
`
Does that make sense?

**Comment by karljj1** [comment]
Hmm this would give me `You have <color=red>2</color> items`.
I want the whole string to be wrapped with red.
`You have <color=red>2 items</color>`

**Comment by axunonb** [comment]
Replace with
```CSharp
templates.Register("red", "<color=red>{} {:plural:item|items}</color>");
```
and you'll get `You have <color=red>2 items</color>` 
This is still missing the "You have". We can't pass text literals to another formatter.

**Comment by karljj1** [comment]
Yeah the user wanted to have it as a general template that could be applied to any smart string. We managed to get it working by having a nested smart string that would be formatted and then formatted again in the main string.
