### ISSUE TITLE
OverflowException: Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by bogatykh** [axuno/SmartFormat#211]
SmartFormat 2.7.0

Framework: .NET Core 3.1

Steps to reproduce:

`

            string template = "Value: **{VĀLUĒ}**";

            Dictionary<string, object> a = new Dictionary<string, object>();

            var smartFormatter = Smart.CreateDefaultSmartFormat();

            var res = smartFormatter.Format(template, a);

`

Exception:
   at System.Convert.ThrowByteOverflowException()
   at SmartFormat.Core.Parsing.Parser.ParseFormat(String format, String[] formatterExtensionNames)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args)
   at SmartFormat.SmartFormatter.Format(String format, Object[] args)

Code above works in 2.6.2 version of SmartFormat reporting "Invalid character in the selector, Invalid character in the selector".

**Comment by axunonb** [comment]
Thanks. In an effort to show the failing character, unicode was not reflected:
> $"'0x{Convert.ToByte(inputChar):X}': "
> throws for unicode - is used twice in the project

must be changed to
**`$"'0x{Convert.ToUInt32(inputChar).ToString("x")}': "`**
result: '0x100'
