### ISSUE TITLE
Switch tests from using reflection to get values to using internal access.

### ISSUE THREAD

**Issue by karljj1** [axuno/SmartFormat#288]
Hey.
I'm currently going through the 3.0 features and merging what I can into our version(we use an older version of .net), so I'm reading through all the code at the moment, kind of a mini code review ;)
I noticed that in some tests(`ReflectionFormatterTests`) you are using reflection to get at internal values to test them. I have found it simpler and safer to use internal access for this use case. E.G Remove `GetInstanceField` and make the type cache property internal. Then use `assembly: InternalsVisibleTo` to give your tests internal access.

**Comment by axunonb** [comment]
Gosh, I remember, This has not found its way from the brain to the to-do list 😉
There should also be a test case for `SmartSettings.IsThreadSafeMode` enabled / disabled.
Gonna fix that.

**Comment by axunonb** [comment]
Closed with PR #291
