### ISSUE TITLE
Errors when trying to use allowed character in list template

### ISSUE THREAD

**Issue by karljj1** [axuno/SmartFormat#297]
I read in the 3.x features that we can now use any character, e.g we can have a `|` as literal. 
For example, I created this string:

```
-------------------------------
First Name | Last Name  |   Age 
-------------------------------
{0:list:{name,-10} \| {lastName,-10}  \| {age,5} |\n}
```

I want to output a list of names that are aligned with the list. 
I get this error:

```
-------------------------------
First Name | Last Name  |   Age 
-------------------------------
John       \ Error parsing format string: No source extension could handle the selector named "lastName" at 120
```

If I remove the `\|` then it works fine. Am I misunderstanding things? I did some quick debugging and I could see that it was being parsed correctly however when I looked at the ToString of the Literal for `\|` I got the exception `System.ArgumentException: Unrecognized escape sequence "\|" in literal.`.

**Smart.Format version**: 
3.1.0

**Framework version**:  (e.g. net5.0)
Unity

**Comment by karljj1** [comment]
I think this may be a bug in the List Formatter Split method.

**Comment by axunonb** [comment]
> I read in the 3.x features that we can now use any character, e.g we can have a `|` as literal.

"Any character" as long as it doesn't interfere with "magic literals" like the `|` which is the default `ListFormatter.SplitChar`.
The `ListFormatter.SplitChar` can be changed to another one that must validate with `ListFormatter.GetValidSplitCharOrThrow(char)`. Actually I considered these "magic literals" can be escaped, but that would have been a lot more complicated.
Did I get your issue right?
