### ISSUE TITLE
May formatter options contain Placeholders

### ISSUE THREAD

**Issue by grendo** [axuno/SmartFormat#310]
Hi the following works

Assert.AreEqual("mystring substring is STRING", sf.Format("mystring substring is {mystring.ToUpper:substr(2)}", new {mystring="mystring",startPosition=2}));

but this fails

Assert.AreEqual("mystring substring is STRING", sf.Format("mystring substring is {mystring.ToUpper:substr({startPosition})}", new {mystring="mystring",startPosition=2}));

NUnit.Framework.AssertionException: '  Expected string length 28 but was 31. Strings differ at index 22.
  Expected: "mystring substring is STRING"
  But was:  "mystring substring is substr(2)"
  ---------------------------------^
  
 Is there a way to make the options of a formatter dynamic ?  If you try and nest the options it seems to ignore the formatter.
 
 I am creating a custom formatter that I want to pass multiple parameters to driven by the data object I pass to SmartFormat.

**Comment by axunonb** [comment]
Yes, indeed, there is a (yet experimental) [`LogicCalFormatter`](https://github.com/axuno/SmartFormat/tree/pr-ncalc-formatter) which dynamically evaluates the **`Format`** part. This goes back to #299.  See the following example to demonstrate the "dynamic" evaluation:
```CSharp
Smart.Default.FormatterExtensions.Add(new LogicCalFormatter());
var data = new { Arg1 = 3, Arg2 = 4 };
_ = Smart.Format("{:M():({Arg1} + {Arg2}) * 5}");
// result: 35
```

As you can see in the [benchmark results](https://github.com/axuno/SmartFormat/issues/299#issuecomment-1221407732) for the `LogicCalFormatter`, this has a notable performance impact. We're working on that before releasing.

Including variables in the `FormatterOptions` would be very difficult (to extract the `Placeholder`s). So currently the parser ignores `Placeholder`s in `FormatterOptions`.

In case you don't care too much about performance and rather look for a quick solution, [here](https://github.com/axuno/SmartFormat/discussions/298#discussioncomment-3170967) is an example, how to evaluate the `Format` with the current API. Kind of Q&D, but it works for the `Format` part.
