### ISSUE TITLE
How to make JObject work in v3.2.0

### ISSUE THREAD

**Issue by denisenko93** [axuno/SmartFormat#316]
Hi! Thanks for reporting this bug! 

Please fill in the relevant information from this template so that we can help you best.

**Smart.Format version**: 3.2.0

**Framework version**:  net6.0

- Please provide a working source code example to reproduce the bug
- What is the current result?
- What is the expected result?
- Please post full exception details if applicable (message, stacktrace, inner exceptions)
- Did you find a workaround? yes/no
- Is there a version in which it worked? 
- Can you help us by writing an unit test?

Formatting with JObject data does not work. It works fine in 2.7.3 version.
Example: 
```
using Newtonsoft.Json.Linq;
using SmartFormat;
					
public class Program
{
	public static void Main()
	{
		object Data = JObject.FromObject(new { OrderId = 1234 });
		//Data = new { OrderId = 1234 }; //works
		

        string SmsText = Smart.Format("Доброго дня! Ваше замовлення №{OrderId} прийнято. Дякуємо за покупку.", Data);
	}
}
```

**Comment by axunonb** [comment]
Could you please elaborate "does not work"?
E.g. which NuGet package are you using, does it throw, what was the expected result or alike...

**Comment by Liklainy** [comment]
Probably you should add an extension source `NewtonsoftJsonSource`, which handles `JObject`
https://github.com/axuno/SmartFormat/wiki/Data-Source-Extensions#newtonsoftjsonsource
https://github.com/axuno/SmartFormat/wiki/Data-Source-Extensions#register-data-sources

**Comment by denisenko93** [comment]
Thank you. It works
```
using System;
using Newtonsoft.Json.Linq;
using SmartFormat;
using SmartFormat.Extensions;
					
public class Program
{
	public static void Main()
	{
		var smart = Smart.CreateDefaultSmartFormat().AddExtensions(new NewtonsoftJsonSource());
		object Data = JObject.FromObject(new { OrderId = 1234 });

        string SmsText = smart.Format("Доброго дня! Ваше замовлення №{OrderId} прийнято. Дякуємо за покупку.", Data);
		
		Console.WriteLine(SmsText);
	}
}
```
