### ISSUE TITLE
PluralLocalizationFormatter: Plural rule for Polish language

### ISSUE THREAD

**Issue by daniel-luberda** [axuno/SmartFormat#317]
locale: pl

SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Invalid number of plural parameters in PluralLocalizationFormatter at 57
{SomeString:{SomeString}| - / {SomeAltString}}
---------------------------------------------------------^

1. It's not event plural form, but string "{0:default|null or empty}" case. Why 3 plural forms are enforced? 
2. Why for some languages (eg. pl) we're forced to always use 3 plural forms. Shouldn't the last one be optional?
3. Until 3.1.0 everything worked fine.

BTW: Thanks for cool lib.

**Comment by axunonb** [comment]
There should be no different behavior between v3.1.0 and v.3.2.0 for Polish localization,
and after running the unit tests for PL there actually is no difference: It gives the correct result with 3 plural forms, but throws with only 2.

Polish has a rule for "one", "few" and "many" according to [this description](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) which is implemented for Polish:
```cs
private static PluralRuleDelegate Polish => (value, pluralWordsCount) =>
    value == 1 ? 0 : // one
    (value % 10).Between(2, 4) && !(value % 100).Between(12, 14) ? 1 : // few
    (value % 10).Between(0, 1) || (value % 10).Between(5, 9) || (value % 100).Between(12, 14) ? 2 : // many
    3;
```
You think this not valid for Polish?

**Comment by daniel-luberda** [comment]
It should definitely be optional. See example for polish `You've got N message[s]`:

```
- Masz 1 wiadomość
- Masz 2 wiadomości
- Masz 3 wiadomości
- Masz 4 wiadomości
- Masz 5 wiadomości
- Masz 6 wiadomości
- Masz 7 wiadomości
- Masz 8 wiadomości
- Masz 9 wiadomości
- Masz 10 wiadomości
- Masz 11 wiadomości
- Masz 12 wiadomości
- Masz 13 wiadomości
```

As you see, two plural forms for this case are just fine. That's why I'm curious why 3 forms are always enforced. Plus, you loose compatibility when another locales are used. Eg. user changes his locale setting, and suddenly app gives exceptions as templates are not valid anymore. (but worked fine on other locale config)

> Testing for null you better use the NullFormatter.

What about NullOrEmpty? For this, `{0:default|null or empty}` is a handy format. Why it cannot be used in `pl` locale? (as it's written in docs)

> There should be no different behavior between v3.1.0 and v.3.2.0 for Polish localization,
It may be earlier version, not `3.1.0`. Sorry for misleading.

**Comment by axunonb** [comment]
> `{0:default|null or empty}`

in v3.x  the name for `DefaultFormatter` is "d", but this format string does not work

> What about null or empty?

`Smart.Format("{0:choose(null|):null|empty|{}}", default(string?)))  // "null"`
`Smart.Format("{0:choose(null|):null|empty|{}}", "")) // "empty"`
`Smart.Format("{0:choose(null|):null|empty|{}}", "something else"))  // "something else"`

> It should definitely be optional

@karljj1 You're using `PluralLocalizationFormatter` a lot. Make more than 2 args generally optional?

**Comment by karljj1** [comment]
> s locale

Having an error when the wrong number of plurals is provided is a really nice way to catch issues early on. I don't think it should go but maybe make it optional and enabled by default?

**Comment by axunonb** [comment]
> optional and enabled by default

Yes, I'll have a look, how this could be implemented.
@daniel-luberda  Your opinion?

**Comment by daniel-luberda** [comment]
I just wanted to bring out possible confusion when running app using `SmartFormat` on different locale setting, which was my case too. I used templates which worked totally fine on one machine, but on the other - it failed (polish locale set). It took a while to debug it. Sure, currently the code is modified to use custom locale settings, but is it an expected behaviour? What's more interesting, this specific case template was language independent (just joining some db data). @karljj1 As you see, it didn't catch the error early enough :)

Maybe adding some info about `PluralLocalizationFormatter` changes to the migration guide could be enough. I don't have any strong opinion what should be done.

```
1 miesiąc
2 miesiące
5 miesięcy
```

That's also correct. There can be both 2 or 3 plural args in Polish.

**Comment by axunonb** [comment]
Updated the Wiki: 
Sections for `PluralLocalizationFormatter` and migration now contain notes regarding mandatory number of arguments that depend on the locale in use.
