### ISSUE TITLE
How to format a DateTime as short date string

### ISSUE THREAD

**Issue by huangyedie** [axuno/SmartFormat#318]
Hi! Thanks for reporting this bug! 

Time Type Operation . 
For example, when I enter 2022-10-18 at 08:00:00, I want to reduce 8 hours to 2022-10-18 at 00:00:00. How to operate
**Smart.Format version**: 

**Framework version**:  (e.g. net5.0)

- Please provide a working source code example to reproduce the bug
- What is the current result?
- What is the expected result?
- Please post full exception details if applicable (message, stacktrace, inner exceptions)
- Did you find a workaround? yes/no
- Is there a version in which it worked? 
- Can you help us by writing an unit test?

**Comment by axunonb** [comment]
```CSharp
[Test]
public void Issue_318()
{
    var data = new { TheDate = new DateTime(2022, 10, 18, 8, 0, 0) };

    var result = Smart.Format("{TheDate.ToShortDateString}", data);
    // short date depends on chosen locale
    result = Smart.Format("{TheDate:yyyy-MM-dd}", data);
    // result: "2022-10-18"
}
```

**Comment by huangyedie** [comment]
That's not the truth. be similar to. Net code : DateTime.Now.AddHours(-8);  AddHours It can be any number

**Comment by axunonb** [comment]
> `DateTime.Now.AddHours(-8)`

Not sure, what you mean, so a working sample would be helpful.

In case you're thinking about `DateTime.Now.AddHours(-8)` should be inside the format string, this is not possible. The `DateTime` should be (part of) an argument to `Smart.Format`.

**Comment by axunonb** [comment]
Closed after missing feedback.
