### ISSUE TITLE
Correct Hungarian plurality rule?

### ISSUE THREAD

**Issue by ATimmeh33** [axuno/SmartFormat#337]
**Smart.Format version**: 3.2.1 (also tested on 2.3.1.1)

**Framework version**:  net6.0

Code:
```
using System.Globalization;

for (int i = 0; i < 10; i++) {
	var data = new {
		Length = i,
	};

	string value = SmartFormat.Smart.Format(
		new CultureInfo("hu"),
		"{Length:an apple|{} apples}",
		data);

	Console.WriteLine(value);
}
```

Project:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SmartFormat.NET" Version="3.2.1"/>
  </ItemGroup>
</Project>
```

Result:
```
➜  ConsoleApp dotnet run
an apple
an apple
an apple
an apple
an apple
an apple
an apple
an apple
an apple
an apple
```

Expected:
```
➜  ConsoleApp dotnet run
0 apples
an apple
2 apples
3 apples
4 apples
5 apples
6 apples
7 apples
8 apples
9 apples
```

Ran into this when one of our unit tests failed when we tried to add support for Hungarian. When I look into plurality rules for Hungarian it doesn't seem much different from English (http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html), however results are very different from expected results (see above).

User error or is SmartFormat broken for Hungarian?

**Comment by axunonb** [comment]
Hungarian is defined as `PluralRules.Singular`, while English is `PluralRules.DualOneOther`. 
Reviewing the [Unicode Language Plural Rules](http://www.unicode.org/cldr/cldr-aux/charts/22/supplemental/language_plural_rules.html) that we use to refer to I'd conclude that `PluralRules.Singular` was correct. The [localization guide](http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html) you mentioned, however, [is different](https://translations.launchpad.net/+languages/hu) from that. (Sometimes even native speakers argue about 'right' or ' wrong'.)

Hungarian is not a language I speak, so I'd appreciate some assistance with this issue.

**Comment by ATimmeh33** [comment]
@axunonb  I am inclined that the rule is perhaps correct. So if we have a format of "a document|{} documents" and we want the amount to be displayed for Hungarian it would be wise to simply have the singular also use "{}" instead of the Hungarian equivalent of "a"? Or is there a way of formatting that it will use "a" only for exactly 1 within SmartFormat?

**Comment by axunonb** [comment]
Sorry, getting certain singular or plural words like the [javascript `Intl.PluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules) do is not implemented in `PluralLocalizationFormatter`. This would be nice, but kind of huge to implement. Sure you could use e.g. the `ChooseFormatter` but I think this is not ideal for this kind of localization.
