### ISSUE TITLE
Nullable notation should work with dictionary source root element

### ISSUE THREAD

**Issue by ddbtrmatic** [axuno/SmartFormat#359]
**Is your feature request related to a problem? Please describe.**
Nullable notation was added for object sources - https://github.com/axuno/SmartFormat/pull/176

However, this feature does not appear to work for dictionary sources when the root element is possibly missing.

**Describe the solution you'd like**

```C#
        [Test]
        public void Dictionary_Dot_Notation_Nullable()
        {
            // dictionary has no entries
            var addrDict = new Dictionary<string, object>();
                     
            const string format = "Address: {City?}";

            var expected = $"Address: ";

            var smart = new SmartFormatter();
            smart.AddExtensions(new ISource[] { new DefaultSource(smart), new DictionarySource(smart) });
            smart.AddExtensions(new IFormatter[] {new DefaultFormatter()});

            var result = smart.Format(format, addrDict);

            Assert.That(result, Is.EqualTo(expected));
           // fails with error 
           // SmartFormat.Core.Formatting.FormattingException: Error parsing format string: No source extension could handle the selector named "City"
        }
```

**Describe alternatives you've considered**

I tried wrapping the dictionary into an object and accessing it with `data.City?`. The only working solution I've found is to convert the dictionary to an object explicitly using something like the following.

```C#
dynamic eo = data.Aggregate(new ExpandoObject() as IDictionary<string, Object>,
                            (a, p) => { a.Add(p); return a; });
```

**Comment by axunonb** [comment]
Adding an empty `Dictionary` as a data source has the same effect as supplying no data at all.
Nullability is about the following use case:
`var addrDict = new Dictionary<string, object?>{{"City", null}};`

In the example with `data.Aggregate` the type of `data` is unclear, but with `a.Add(p)` obviously a `KeyValuePair<string, object>` is added.

Hope this helps.

**Comment by ddbtrmatic** [comment]
I understand and thank you for your reply. However, maybe I should rephrase the request. I'm looking for the option to ignore, or preferably, treat as null, placeholders that are not found in the dictionary. My particular use case for this is that I have dynamic sets of data, and formatting should not always fail when a particular field is missing.

Setting the `ErrorAction` to `Ignore` is a work-around. However, I would like to continue to report other errors when they do occur, so this isn't the best option for me.

I attempted to write my own `OptionalDictionarySource`, with something like the following, but ran into a few problems.

- The `nullable` operator check doesn't appear to detect an ending `?` on a root placeholder, i.e. `{placeholder?}`.
- `DataSource.HasNullableOperator` is private. It would be helpful to mark this as `protected` or even `protected virtual` to make creating a custom a `DataSource` easier.

```C#
    public class OptionalDictionarySource : Source
    {
        /// <inheritdoc />>
        public override bool TryEvaluateSelector(ISelectorInfo selectorInfo)
        {
            var current = selectorInfo.CurrentValue;
            if (TrySetResultForNullableOperator(selectorInfo)) return true;

            if (current is null) return false;

            var selector = selectorInfo.SelectorText;

            // See if current is an IDictionary (including generic dictionaries) and contains the selector:
            if (current is IDictionary rawDict)
            {
                foreach (DictionaryEntry entry in rawDict)
                {
                    var key = entry.Key as string ?? entry.Key.ToString()!;

                    if (!key.Equals(selector, selectorInfo.FormatDetails.Settings.GetCaseSensitivityComparison()))
                        continue;

                    selectorInfo.Result = entry.Value;
                    return true;
                }

                // NEW OPTIONAL DICTIONARY CHECK
               // if placeholder ends in a question mark, i.e. {placeholder?},
                // then treat the same way as a nullable field, i.e. {placeholder.field?.otherField}
                //
                // alternatively, provide an option to treat missing dictionary entries as nullable.
                if (HasNullableOperator(selectorInfo))
                {
                    selectorInfo.Result = null;
                    return true;
                }
            }
```

**Comment by axunonb** [comment]
- Your correct, the `nullable` operator is always part of the next selector.
- The `Source.HasNullableOperator` method is private, but it's possible to use the code inside it to get the value in a custom `ISource`.
- It might be more simple in your use case, to add a "fallback source" as the the last registered `ISource`, which returns a `null` value if a variable was not found. So the "null-if-missing" behavior is always available.

**Comment by ddbtrmatic** [comment]
Thank you for the suggestion, it was not something I had considered. I agree that providing a fallback source is a better way to handle it, and will provide me the flexibility I am looking for.
