### ISSUE TITLE
PluralRule for DualFromZeroToTwo: Does not cover value of 2

### ISSUE THREAD

**Issue by axunonb** [axuno/SmartFormat#369]
### Discussed in https://github.com/axuno/SmartFormat/discussions/363

<div type='discussions-op-text'>

<sup>Originally posted by **Fuitad** December  4, 2023</sup>
Heya,

I'm trying to understand why French is set to DualFromZeroToTwo instead of DualOneOther like English. I'm French Canadian and I'm having a hard time understanding why

``{0:plural:No object|{} object|{} objects} cached on file system`` is working in English but ``{0:plural:Aucun objet|{} objet|{} objets} en cache sur le système`` in French is giving me ``SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Invalid number of plural parameters in PluralLocalizationFormatter``

Maybe there's something in FR-FR that explains this? But on a French Canadian point of view, this doesn't make much sense.</div>

**Comment by axunonb** [comment]
@karljj1 @Fuitad 
`PluralRules` is very old code that had rarely been touched. So we should be careful with changes.
Please have a critical look at the draft PR https://github.com/axuno/SmartFormat/tree/pr/plural-rules
Besides the fix for `pluralWordsCount == 2` for I tried to make `DualFromZeroToTwo` more consistent for different `pluralWordsCount`.
Your feedback is very welcome.

**Comment by karljj1** [comment]
> @karljj1 @Fuitad `PluralRules` is very old code that had rarely been touched. So we should be careful with changes. Please have a critical look at the draft PR https://github.com/axuno/SmartFormat/tree/pr/plural-rules Besides the fix for `pluralWordsCount == 2` I tried to make `DualFromZeroToTwo` more consistent for different `pluralWordsCount`. Your feedback is very welcome.

The link doesnt seem to work, it just takes me to the main repo page. I cant see any PRs, maybe I dont have permission to see it?

**Comment by axunonb** [comment]
PR submitted right now: https://github.com/axuno/SmartFormat/pull/370
