### ISSUE TITLE
ParsingErrors exception on perfect format string.

### ISSUE THREAD

**Issue by israellot** [axuno/SmartFormat#374]
I'm trying to reproduce a weird exception I'm occasionally seeing on logs. 
Somehow it complains about a missing bracket, but clearly there's nothing missing.  

![image](https://github.com/axuno/SmartFormat/assets/840042/75d15afa-b211-433e-ae7f-1b27a1490a7a)

This is on version 3.2.2

**Comment by axunonb** [comment]
Hi, without a complete working sample this is hard to figure out.
But as you're saying, that this is happening occasionally, you might be running `SmartFormat` in a multi-threaded context without `SmartSettings.IsThreadSafeMode = true`. Please try to apply this setting.

**Comment by axunonb** [comment]
Can we close this issue?
