### ISSUE TITLE
Static cache for ReflectionSource and DictionarySource?

### ISSUE THREAD

**Issue by axunonb** [axuno/SmartFormat#425]
@karljj1 Are these variables **not** `static` by mistake? Can't remember a reason to make them instance variables 😉. Can you help me out?

https://github.com/axuno/SmartFormat/blob/421c7155b47d8e819a0a75a392f2b19f2c56e7bd/src/SmartFormat/Extensions/ReflectionSource.cs#L32

https://github.com/axuno/SmartFormat/blob/421c7155b47d8e819a0a75a392f2b19f2c56e7bd/src/SmartFormat/Extensions/DictionarySource.cs#L82

**Comment by karljj1** [comment]
They could be static. We typically only have 1 ReflectionSource in the project so it didn't matter much.

**Comment by axunonb** [comment]
Now I remember. It's about case-sensitivity settings. Once the cache is created, case-sensitivity for the cache dictionary cannot change. But still: It should become `static`.

**Comment by axunonb** [comment]
Although we can say this is very unlikely to break existing code - potentially it could. Would pointing out the change in the release notes suffice?

**Comment by karljj1** [comment]
> Now I remember. It's about case-sensitivity settings. Once the cache is created, case-sensitivity for the cache dictionary cannot change. But still: It should become `static`.

I agree. Do you think we should have a different cache for each type of case sensitivity or maybe clear it when it's changed?
