### ISSUE TITLE
It would be nice if SmartExtensions methods returned the StringBuilder instead of void

### ISSUE THREAD

**Issue by Klikini** [axuno/SmartFormat#451]
**Is your feature request related to a problem? Please describe.**

Normally, `StringBuilder`'s methods return the original `StringBuilder` object, so they are chainable:
```cs
=> new StringBuilder().Append("<p>").Append(content).AppendLine("</p>").ToString();
```

However, `AppendSmart` and `AppendLineSmart` return `void`, so they are not chainable:
```cs
=> new StringBuilder().Append("<p>").AppendSmart(format, arg)/* NOPE */.AppendLine("</p>").ToString();
```

**Describe the solution you'd like**

This fix should be as simple as replacing the `void` return type of `SmartExtensions.AppendSmart` and `SmartExtensions.AppendLineSmart` with `StringBuilder` and adding `return sb;` to the ends of the methods.

_I'm happy to submit a PR if it's a welcome change!_

**Describe alternatives you've considered**

There's not a *problem*, but the lack of chaining means instead of:

```cs
return new StringBuilder().Append("<p>").AppendSmart(format, arg).AppendLine("</p>").ToString();
```

I have to write:

```cs
var output = new StringBuilder();
output.Append("<p>");
output.AppendSmart(format, arg1);
output.AppendLine("</p>");
return output.ToString();
```

**Comment by axunonb** [comment]
> I'm happy to submit a PR if it's a welcome change!

Yes, it is, thanks :)
